### ISSUE TITLE
Catalog improvements

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#273]
* [x] Add "Search all" option to categories grid
 * [x] Share categories and mosaic components and try to make it one single component
 * [x] Thematic views: remove objects icon
 * [x] Thematic views: implement add to map reading layers config from external json (as in metadata)
 * [ ] Objects: implement add to map
 * [x] Objects: implement Infobox show on item click

**Comment by kappu72** [comment]
Thematic views addToMap:
I'll read layers from json map config file and I'll add layers to app mapconfig store
