### ISSUE TITLE
Implement the QueryBuilder UI component and related ecosystem

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#5]
* [x] ComboField
 * [ ] HierarchicalComboField (https://github.com/geosolutions-it/csi-sira/issues/17)
 * [ ] DateField
 * [ ] SpatialFilterField
 * [ ] FilterComposerField(s)
 * [ ] FormBuilder (https://github.com/geosolutions-it/csi-sira/issues/12)
 * [ ] QueryBuilder
 * [ ] QueryRun Action

https://docs.google.com/document/d/1ZDAkZkz193_oXU4NLHi5MTVg0K9PITuMm2CB1ONQePs/edit?usp=sharing

**Comment by ridethepenguin** [comment]
![by_attr_static](https://cloud.githubusercontent.com/assets/4783655/12548293/9684b8a4-c355-11e5-9938-94affc073b8e.png)

Wireframe for a query builder **Query by attribute** panel, built from a static set of fields.

![by_attr_dynamic](https://cloud.githubusercontent.com/assets/4783655/12548323/caeea3b6-c355-11e5-8d9b-034d567806ea.png)

Wireframe for a query builder **Query by attribute** panel, dynamically built from resource metadata.

**Comment by mbarto** [comment]
I would not use the checkbox for enabling fields. Let's put a "no value" in each combo and empty text in textfields to get the same behaviour.

**Comment by ridethepenguin** [comment]
Wireframe for query builder **Spatial filter** panel.

* User defines the shape of the spatial filter:

![shape_selection](https://cloud.githubusercontent.com/assets/4783655/12548940/0c4b9e82-c35a-11e5-8bd1-3254846c39ce.png)

* **Buffer**, **Bounding Box** require additional options:

![buffer_options](https://cloud.githubusercontent.com/assets/4783655/12549062/0697977e-c35b-11e5-8ffc-2c59b774f2ba.png)
![bbox_options](https://cloud.githubusercontent.com/assets/4783655/12549142/88691836-c35b-11e5-98d1-2c05ab2c8c54.png)

**Circle**, **Polygon** must be drawn on map:

![circle](https://cloud.githubusercontent.com/assets/4783655/12549217/00159bf2-c35c-11e5-8c81-5d45d53c2ee2.png)
![polygon](https://cloud.githubusercontent.com/assets/4783655/12549220/03b71c18-c35c-11e5-9253-82bc657ff260.png)

* Finally, geometric operator is selected:

![geometry_operation](https://cloud.githubusercontent.com/assets/4783655/12549231/19f8b9f0-c35c-11e5-8d7a-74e3ee5585a5.png)


**FULL EXAMPLE**:

![spatial_filter_full_example](https://cloud.githubusercontent.com/assets/4783655/12549261/5c9fb7f4-c35c-11e5-9333-81ce270a3d8e.png)

**Comment by ridethepenguin** [comment]
Updated wireframe for **Query by attribute** panel (static set of fields):
* removed checkboxes to enable/disable filters, *-- n.a. --* or some other *NO VALUE* option is used instead
* added missing field *Operazioni di recupero*
* added explanatory comments

![by_attr_static_v2](https://cloud.githubusercontent.com/assets/4783655/12549864/6bc3546c-c360-11e5-8f18-ce741a578cba.png)
