### ISSUE TITLE
Check for missing backports

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/csi-sira#725]
Review eventual [MapStore2 csi-sira branch](https://github.com/geosolutions-it/MapStore2/tree/csi_sira) fixes and improvements not ported to master.

Advise: try to compare master and csi-sira commits from 17 Dec 2019 backward to find eventual missing commits, have a look in particular at commits from:

- Mar 16, 2017
- Jun 5, 2017
- Dec 17, 2019

The target it to check if all relevant fixes/improvements provided in csi-sira branch have been backported to MS master branch.

And fix if any compatibility issues with the upgrade

- Check if FeatureGrid of latest version Mapstore can be used

**Comment by dsuren1** [comment]
Except for feature grid commit(#733) which will be handled in separate issue, rest have been identified as not necessary
