### ISSUE TITLE
MapStore Upgrade deploy and CD setup

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/csi-sira#730]
With this epic issue #720 we are working on the update of the SIRADEC downstream project to the latest MapStore.
As soon as the PR #729 is merged, we need to deploy the updated SIRADEC project in a new instance next to the old one (use a separate Tomcat instance for this): the old instance will be used as a reference for testing.

A continuous deploy must be provided for this new SIRADEC instance, the temporary update branch must be used for this **[ms_update](https://github.com/geosolutions-it/csi-sira/tree/ms_update)** (all PRs for the update are provided there).

The deploy doc [here](https://docs.google.com/document/d/1WOqjaVQ8pUYKQI81frT7WUubsOm9zeNQD9Rm5fLt_D8/edit)

**Comment by randomorder** [comment]
@giacomoc92 
Please set up a clone of the existing decsiraweb tomcat instance and create a jenkins job to build and deploy the application according to @tdipisa 's instructions (remember for the eploy part you can at least in part reuse what you made in [the jenkins job for GeoServer](https://build.geo-solutions.it/jenkins/job/Decsira_GeoServer_deploy/))

**Comment by randomorder** [comment]
updates @giacomoc92 ?

**Comment by giacomoc92** [comment]
Tomcat instance has been cloned and is running on port 8083 alongside the old instance.

http://decsira-dev.geo-solutions.it:8083/decsiraweb/map.html#/map/A

Process logged here 
https://docs.google.com/document/d/1WOqjaVQ8pUYKQI81frT7WUubsOm9zeNQD9Rm5fLt_D8/edit#heading=h.q9bs2my8q1k0

tomorrow I will go on with the jenkisn job

**Comment by giacomoc92** [comment]
Building from the build scripts
```sh
#!/bin/bash
set -e

cd frontend
npm install
npm run compile
npm run lint
# npm test
cd ..
mvn clean install
```
 yields this error: 
`npm ERR! code EINTEGRITY
npm ERR! sha512-iWx+oupEjIH7KA4mYZKlPS/C7by3/aVcFPmFq6P/DYeoa3m3NH0ojTuvrwBBkJcUPbLN2yAhFmcU2jRJpxQGnw== integrity checksum failed when using sha512: wanted sha512-iWx+oupEjIH7KA4mYZKlPS/C7by3/aVcFPmFq6P/DYeoa3m3NH0ojTuvrwBBkJcUPbLN2yAhFmcU2jRJpxQGnw== but got sha512-y3JaeRSplks6NYQuCOj3ZFMO3j60rTwbuKCvZxsAraGYH2epusatvZ0baZYA01WsGqJBq/Dl6vOrMUJqyMj8kA==.`

and running the same commands without moving to frontend seems to produce the war just fine https://build.geo-solutions.it/jenkins/view/csi_piemonte/job/SIRADEC%20Build/25/console

is this normal? @randomorder

**Comment by giacomoc92** [comment]
I have kept going forward with the deploy job https://build.geo-solutions.it/jenkins/view/csi_piemonte/job/SIRADEC%20Deploy/

But there are issues with the new deployed app. 

http://decsira-dev.geo-solutions.it:8083/decsiraweb/map.html#/map/A returns 404

catalina.out 
![image](https://user-images.githubusercontent.com/49372260/90662780-14f03d00-e249-11ea-88e6-355560b300b7.png)

this does not happen with a manual deploy, se the problem must be in the build

**Comment by mbarto** [comment]
@giacomoc92 @dsuren1 the npm-shrinkwrap.json file is something we stopped using on recent MapStore based projects (it was used before package-lock.json support was introduced in npm), so I think we can remove the file from the repository right away.

**Comment by dsuren1** [comment]
> @giacomoc92 @dsuren1 the npm-shrinkwrap.json file is something we stopped using on recent MapStore based projects (it was used before package-lock.json support was introduced in npm), so I think we can remove the file from the repository right away.

**Comment by randomorder** [comment]
Thanks @dsuren1 @mbarto 

Jenkins build worked and the application should be updated now https://decsira-dev.geo-solutions.it/decsiraweb/
Please let me know @mbarto

**Comment by mbarto** [comment]
@randomorder at the given url I still see the old (not updated) frontend. I believe we asked to have the new frontend and the old frontend accessible at two different urls. Do you know the status of this and where eventually the new frontend can be reached?

**Comment by randomorder** [comment]
> @randomorder at the given url I still see the old (not updated) frontend. I believe we asked to have the new frontend and the old frontend accessible at two different urls. Do you know the status of this and where eventually the new frontend can be reached?

hmm. I guess the URL in the Jenkins job was not updated and is still pointing to the old application then.

I'll find out

**Comment by mbarto** [comment]
@randomorder remember the idea is to have access to both, so that we can easily compare the new and the old

**Comment by randomorder** [comment]
Yes, I can see both instances running. One is missing the reverse proxy mapping in Apache. I'll fix it in a minute

**Comment by randomorder** [comment]
https://decsira-dev.geo-solutions.it/decsiraweb2/
