### ISSUE TITLE
Identify behaviour is not the same as the previous version

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#751]
In the map page (https://decsira-dev.geo-solutions.it/decsiraweb2/map.html#/map/), identify is not showing results in the correct format.

**External WMS layers**
For external WMS layers, default to be used for the ‘Feature identify’ / ‘Informazione sulla Feature’ is HTML. 
Please check with WMS that have only TEXT for the GetFeatureInfo results, the result has to be visible too.
e.g.: http://geomap.reteunitaria.piemonte.it/ws/vtdifsuolo/rp-01/rmepaiwms/wms_vtdifsuolo_aree_rme?service=WMS&version=1.1.1&request=getCapabilities

As you can see in DECSIRA 1, all the different types of results are visible in the same identify window: TEXT and HTML.  

![image](https://user-images.githubusercontent.com/2770528/94115270-c63a5200-fe49-11ea-84bb-1291935a90c6.png)
![image](https://user-images.githubusercontent.com/2770528/94115297-d2261400-fe49-11ea-8818-6c4764b5df15.png)

**Data from internal catalog**
The feature identify for ‘DECSIRA Service’ (I mean the service WFS 2.0) should use custom templates (see the files ‘infoTemplate*.jxst’ https://github.com/geosolutions-it/csi-sira/tree/master/frontend/assets).

This is the actual results:

![image](https://user-images.githubusercontent.com/2770528/94117569-aa847b00-fe4c-11ea-9240-ef2ad3d98c22.png)

This was in previous version:

![image](https://user-images.githubusercontent.com/2770528/94117659-cee05780-fe4c-11ea-98f6-0bfadfc84c33.png)

**Comment by mbarto** [comment]
@dsuren1 this is mostly done, I would only ask you to check this: I think in the old version there was some form of fallback when a format was not supported by the server.
For example: if you choose HTML, but this is  not supported by the service, you fallback to showing TEXT. Can you check if you can find this behaviour in the old application, and eventually if it can be reproduced in the current one?

**Comment by dsuren1** [comment]
@mbarto 
The only fallback infoFormat logic is this. First check is on the layer, if found uses it else uses format set by the user
> const infoFormat = layer.infoFormat ? this.infoFormat(layer.infoFormat, newProps.infoFormat) : newProps.infoFormat;

The only difference I found is the default state of mapInfo's  infoFormat is text/html (old) vs text/plain (current), which I can change it back

**Comment by mbarto** [comment]
@dsuren1 yes please, let's change it back
