### ISSUE TITLE
Query builder windows should be resizable

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#752]
In the Map page (https://decsira-dev.geo-solutions.it/decsiraweb2/map.html#/map/)

The query builder window box must be able to be enlarged. 
See DECSIRA 1: this enlargement functionality is made active by a small icon at the bottom right of the QB window

![image](https://user-images.githubusercontent.com/2770528/94115608-43fe5d80-fe4a-11ea-8517-04b6bae60fcd.png)

I see in this link page below that the feature is present, so I guess it still needs to be integrated
https://decsira-dev.geo-solutions.it/decsiraweb2/SiraNoMap.html?featureType=impiantoRifiutiAuaNoAua#/A

**Comment by dsuren1** [comment]
@mbarto 
If this what your are referring too, then I can enlarge the query window. Kindly correct me if I'm wrong. Thanks
![enlarge query window](https://user-images.githubusercontent.com/26929983/94395398-3f54e480-017d-11eb-8582-1fbd74177562.gif)

**Comment by mbarto** [comment]
@dsuren1 looking at the document they sent, I see that their screenshot is showing a scrollbar in the query builder window (probably they are shrinking the browser window vertically so that the scrollbar appears). In that case the icon for resizing is not visible. We can have a look if we can easily make this use case working too.

**Comment by dsuren1** [comment]
@mbarto 
Sure, I will make changes so that it works the use case from the client too
