### ISSUE TITLE
Shapefile export doesn't work

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#753]
* In the ‘result list’ the export runs for csv format but not for the shapefile format, it gives an error message, please see below.

Export Data
Errore nel parsing dei dati

 * The botton ‘Export’ color is blue and not green.

url: https://decsira-dev.geo-solutions.it/decsiraweb2/SiraNoMap.html?featureType=impiantoRifiutiAuaNoAua#/A

![image](https://user-images.githubusercontent.com/2770528/94115901-a5263100-fe4a-11ea-9cf3-f89b6132154a.png)

**Comment by dsuren1** [comment]
@mbarto 
I will give a fix for button styling as part of #750 
With respect to exporting, I'm able to export and I have tried with certain filter  conditions too and I couldn't reproduce the issue. Kindly let me know if any specific steps involved. Thanks

![Export](https://user-images.githubusercontent.com/26929983/94395876-43353680-017e-11eb-809b-8e802057ce57.gif)

**Comment by mbarto** [comment]
@dsuren1 try the same, but choosing Shapefile as a format from the combo
