### ISSUE TITLE
Selection on map of search results does not work

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#754]
After using Query Builder to select data from WFS 2.0  – either from the ‘Alfanumeric Filter’ and/or ‘Spatial Filter’ – the result list is correct but if I try to use the "Select All" function on the map, the application gives an error and It’s necessary to reload the DECSIRA application.

![image](https://user-images.githubusercontent.com/2770528/94116217-077f3180-fe4b-11ea-8ab2-71c1823c6220.png)
![image](https://user-images.githubusercontent.com/2770528/94116221-0a7a2200-fe4b-11ea-98e1-09d8ffdbf83e.png)

**Comment by mbarto** [comment]
@dsuren1 I cannot see this one fixed, if I click on "Seleziona tutti" in a list result I don't see anything selected on the map.

**Comment by dsuren1** [comment]
Hi @mbarto 

Kindly confirm if this is what intended
![select_all](https://user-images.githubusercontent.com/26929983/94829393-1ad06500-0428-11eb-87da-967427b9f986.gif)

**Comment by mbarto** [comment]
@dsuren1 yes, does it work for you?

**Comment by dsuren1** [comment]
@mbarto Yes, it seems to. And to be sure I checked it directly on https://decsira-dev.geo-solutions.it/decsiraweb2/map.html#/map/
