### ISSUE TITLE
Zoom to all from lists does not work correctly

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#773]
![image](https://user-images.githubusercontent.com/2770528/95862698-9228c180-0d63-11eb-870c-73e3c7c1a83a.png)

It looks like it is zooming to 0, always. I suspect the bbox of zoom is not calculated properly.

Connect to #720

**Comment by dsuren1** [comment]
@mbarto 
With latest Mapstore, the resolution calculation follows GeoWebCache algorithm, so the resolution generated is different from the old version, so trying to getZoomForExtent returns the zoom of 5 compared to 7 based on the resolution in the old application. Hence the difference. 
Kindly let me know if we have supply a minZoom prop when zoom to all list is performed

**Comment by mbarto** [comment]
@dsuren1 I think there some issue with the algorithm (maybe it doesn't work correctly if the CRS is not EPSG:3857), because the calculated zoom is a lot bigger than the features extent.
If I filter for PROVINCIA = 'ALESSANDRIA' I get this zoom:

![image](https://user-images.githubusercontent.com/2770528/96098218-25800500-0ed2-11eb-944b-f48c84223da2.png)

I would expect something more similar to this:

![image](https://user-images.githubusercontent.com/2770528/96098314-45afc400-0ed2-11eb-8d8b-53a9de55c626.png)

**Comment by mbarto** [comment]
@dsuren1 I don't think the proposed solution is enough, you are basically limiting the zoom so that in one use case (looking for PROVINCIA='ALESSANDRIA') it works. What happens if I look for Comune = 'Acqui Terme', I get the same zoom, but I would expect to zoom closer. Could you have a look at why the extent to zoom alghoritm fails for EPSG:32632? I think that's the root problem.

**Comment by dsuren1** [comment]
Hi @mbarto 
I tried the same in the decsira2 instance. Kindly let me know if I'm missing something. Here I tried with different search criterias and tried zoom to all. 
![zoomtoall](https://user-images.githubusercontent.com/26929983/96260355-8eec3a80-0fdc-11eb-9714-23109bec89b2.gif)

**Comment by mbarto** [comment]
@dsuren1 this is the zoom I would expect for Acqui Terme:

![image](https://user-images.githubusercontent.com/2770528/96264526-930c5e00-0fc4-11eb-8de3-f0599d175480.png)

Instead I get this:

![image](https://user-images.githubusercontent.com/2770528/96264633-ae776900-0fc4-11eb-8f57-0041b7e6585e.png)

I think it's a lot different than the features original extent.

**Comment by mbarto** [comment]
@dsuren1 checked on the current production instance, and it does the same, so I guess you are right, moving to done
