### ISSUE TITLE
Remove Defaults folder from TOC

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#775]
A 'Default' folder appears when I use the Query Builder to find data. 
Can you please try to find a way in which the 'Default' folder no longer appears?

Connected to #720

**Comment by dsuren1** [comment]
Hi @mbarto Kindly let me know how to reproduce this issue

**Comment by dsuren1** [comment]
Never mind. I have reproduced it

**Comment by mbarto** [comment]
@dsuren1 can you tell me how you reproduced it? I would like to test and be sure when it was happening.

**Comment by dsuren1** [comment]
Sure @mbarto . Here are the steps with which I was able to reproduce the issue.
**Steps**:
1. While in query builder, perform a search
2. From the result, highlight the feature by selecting the glass icon on the row
3. Now perform "select all" features
4. Go navigate back to the TOC to no empty 'Default' group is added

**Comment by mbarto** [comment]
ok, thx, then it is fixed
