### ISSUE TITLE
Background selector configuration

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#779]
Is it possible to:

 * remove the delete button on the background thumbnail? 
 * enable OSM background for the SIRA custom CRS?

Connected to #720

**Comment by dsuren1** [comment]
@mbarto 
Both are possible. 
But the OSM background once unselected cannot be selected back (needs refresh) as Mapstore restricts custom CRS (type other than WMS and WMTS) from being selected. Kindly advise if this fine?

**Comment by mbarto** [comment]
@dsuren1 is it possible to remove this restriction on CRS at least for OSM? openlayers can reproject it on the fly, so it really doesn't make sense to deny this possibility. If it is an "easy" change I would try to make a PR on MapStore to remove this constraint. What do you think?

**Comment by dsuren1** [comment]
@mbarto Yes, this should be a simple change. I will create an issue in Mapstore to allow OSM

**Comment by mbarto** [comment]
@dsuren1 with your last fix there is a weird behaviour, both OSM and another background are visible at the same time (I think you put visible: true to both in configuration); I would go back to the old initial configuration, and have OSM initially not visible.

**Comment by dsuren1** [comment]
Sure @mbarto , I will change it accordingly.
