### ISSUE TITLE
MLS - disable buttons if there is no geometry on main feature

### ISSUE THREAD

**Issue by bruncili** [geosolutions-it/csi-sira#804]
When there is no geometry in the returned feature (list or detail, we should not show the MLS icon / button.

![image.png](https://images.zenhubusercontent.com/5f805d3da0586436dbeb970f/0eaf9dc5-7056-4602-ac55-0e08383c1e80)

**Comment by mbarto** [comment]
@dsuren1 are you sure this is fixed? Trying on dev environment:

![image](https://user-images.githubusercontent.com/2770528/99357078-99d00e80-28ab-11eb-8482-fe3bd819d5af.png)

![image](https://user-images.githubusercontent.com/2770528/99357133-b2402900-28ab-11eb-80a4-e629f0d30a53.png)

**Comment by dsuren1** [comment]
@mbarto  I thought the requirement meant geometry type rather the geometry 'coordinates'. I will give a fix in a while.

**Comment by mbarto** [comment]
@bruncili the fix is deployed in TEST environment, and ready to be tested by the customer
