### ISSUE TITLE
Symbols in query builder group of conditions

### ISSUE THREAD

**Issue by bruncili** [geosolutions-it/csi-sira#806]
If the user enters a group of conditions, two symbols are superimposed: the symbol for "add third level group of conditions" and the symbol for "delete group of conditions"

![image.png](https://images.zenhubusercontent.com/5f805d3da0586436dbeb970f/b87e32f2-0217-4b60-b482-2eb03e5eb31c)

**Comment by mbarto** [comment]
@bruncili this is deployed in TEST environment, and ready to be tested by the customer
